-- SQLBook: Code
CREATE TABLE Users (
  User_ID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Gender VARCHAR(10) NOT NULL,
  Birthdate DATE NOT NULL
);

CREATE TABLE MBTI_Test (
  Test_ID INT PRIMARY KEY AUTO_INCREMENT,
  User_ID INT NOT NULL,
  Name VARCHAR(255) NOT NULL,
  Quest VARCHAR(255) NOT NULL,
  FOREIGN KEY (User_ID) REFERENCES Users(User_ID)
);

CREATE TABLE MBTI_Result (
  Result_ID INT PRIMARY KEY AUTO_INCREMENT,
  User_ID INT NOT NULL,
  MBTI VARCHAR(10) NOT NULL,
  Result VARCHAR(255) NOT NULL,
  FOREIGN KEY (User_ID) REFERENCES Users(User_ID)
);

CREATE TABLE Dashboard (
  Dashboard_ID INT PRIMARY KEY AUTO_INCREMENT,
  User_ID INT NOT NULL,
  Nama VARCHAR(255) NOT NULL,
  Gender VARCHAR(10) NOT NULL,
  Birthdate DATE NOT NULL,
  MBTI VARCHAR(10) NOT NULL,
  Stud VARCHAR(255) NOT NULL,
  FOREIGN KEY (User_ID) REFERENCES Users(User_ID)
);